version: '3'

services:
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - 3306:3306
    expose:
      - 3306
