spring:
  application:
    name: gateway-service
  main:
    banner-mode: "off"

server:
  port: 8765

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: user-service
    course:
      path: /course/**
      serviceId: course-service
  ribbon:
    eager-load:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 10000
